- name: Magento 2 actions
  # You may pin to the exact commit or the version.
  # uses: MAD-I-T/magento-actions@76811cf8f0cf5282b0f8481c24fa34ac5a9b032c
  uses: MAD-I-T/magento-actions@v3.21
  with:
    # version of php to use 7.1, 7.2 or 7.4
    php: # optional, default is auto
    # Possible values: build, static-test, integration-test, unit-test, phpcs-test, deploy-staging, deploy-production, cleanup-staging, cleanup-production, security-scan-[files|modules]
    process: # optional, default is build
    # specify themes to build multiple values must be comma separated e.g (Magento/blank or Magento/blank,Magento/luma)
    themes: # optional
    # specify build languages multiple values must be comma separated e.g (fr_FR or fr_FR,nl_NL)
    langs: # optional
    # numbers of builds / releases to keep after deployment (rotation). Possible values (int) e.g: 3
    keep_releases: # optional, default is 3
    # override config and scripts dirs with your own setup/config, must respect default scalfolding 1 or 0
    override_settings: # optional, default is 0
    # your src is using elasticsuite?  1 or 0
    elasticsuite: # optional, default is 0
    # your src is using elasticsearch?  1 or 0
    elasticsearch: # optional
    # your src is using opensearch?  1 or 0
    opensearch: # optional
    # phpcs check on a Magento module or code base. Possible values, Vendor, Vendor/MyModule or dir path using github repository scaffolding
    extension: # optional, default is 
    # MEQP magento coding standard severity check
    severity: # optional, default is 1
    # Magento2, PSR2, PSR1, PSR12 etc... see magento-coding-standard
    standard: # optional, default is Magento2
    # deployer-php custom configs. Possible values, no-permission-check (there will be no permission check of writable dirs)
    deployer: # optional, default is default
    # force composer version. Possible values 1 or 2
    composer_version: # optional, default is 0
    # the magento version to install i.e 2.4.1
    magento_version: # optional, default is 0
    # List of modules to be disabled during install, comma separated e.g: Magento_Sales,Magento_Config
    disable_modules: # optional, default is 
    # enables functionalities when installing magento possible values: pwa
    enable: # optional, default is 
    # do not push magento source code to github repo values 0|1
    no_push: # optional, default is 0
    # custom testsuite to be ran works for integration and unit testing  e.g: "Memory Usage Tests"
    testsuite: # optional
    # integration test filter test in class e.g: testAppReinitializationNoMemoryLeak
    integration_filter: # optional
    # path to integration class path from dev/tests/integration e.g: "./testsuite/Magento/MemoryUsageTest.php"
    integration_class: # optional
    # Unit test custom config path
    unit_test_config: # optional, default is dev/tests/unit/phpunit.xml.dist
    # Run restricted unit test subset directory path
    unit_test_subset_path: # optional
    # path to source to be mess detected
    md_src_path: # optional
    # Ruleset path e.g ruleset path for mess detector
    ruleset: # optional, default is dev/tests/static/testsuite/Magento/Test/Php/_files/phpmd/ruleset.xml
    # path to file or directory to exec, scan, etc... (phpstan)
    exec_path: # optional, default is .
    # node version for pwa-studio
    node_version: # optional, default is 16
    # generic version to be compounded with other variables e.g pwa-studio-install to specify pwa version
    version: # optional
